#include "vector_utils.h"
#include <stdio.h>

static int cmpfunc(const void * a, const void * b)
{
  int a0 = ((int *)a)[0];
  int b0 = ((int *)b)[0];
  if (a0 < b0)
        {
          return -1;
        }
  else if (a0 > b0)
    {
      return 1;
    }
  else
    {
      return 0;
    }
}

void sort_int_vec(int * base, size_t len)
{
  qsort(base, len, sizeof(int), cmpfunc);
}

void _normalize_vec_w_sign(int * vec, size_t len)
/* Let G be an subgroup of the auto group of the lattice generated by
 even sign changes and permutations which change only first len element.
This function converts vec to the representative by the action of G.*/
{
  int mul = 1;
  int len_int = (int)len;
  for (int i = 0; i < len_int; i++)
    {
      if (vec[i] == 0)
        {
          mul = 0;
          break;
        }
      else if (vec[i] < 0)
        {
          mul *= -1;
        }
    }
  for (int i = 0; i < len_int; i++)
    {
      vec[i] = abs(vec[i]);
    }
  sort_int_vec(vec, len);
  if (mul == -1)
    {
      vec[0] *= -1;
    }
}

void normalize_vec_w_indices(int * vec,
                             int * w_sign_indices,
                             int wo_sign_indices_array[8][16])
/* Let v be an int array of length 8 or 16 s.t.
   v = {i_1, ..., i_a, 0, ..., 0} where 0 < i_k < (8 or 16).
   Denote by G(v) a subgroup of the autom group of the lattice
   generated by even sign changes and permutations which change only
   {i_1, ... i_a}th entries.
   Denote by H(v) a similar group for only permutations.

   Let G be a group generated by G(w_sign_indices) and
   H(v) for non-zero array v in wo_sign_indices_array.
   This function converts vec to the representative by the action of G.*/
{
  int vec1[16] = {0};
  int len = 0;
  for (int i = 0; w_sign_indices[i]; i++)
    {
      vec1[i] = vec[w_sign_indices[i]];
      len++;
    }
  _normalize_vec_w_sign(vec1, len);
  for (int i = 0; w_sign_indices[i]; i++)
    {
      vec[w_sign_indices[i]] = vec1[i];
    }

  for (int j = 0; wo_sign_indices_array[j][0]; j++)
    {
      len = 0;
      for (int i = 0; wo_sign_indices_array[j][i]; i++, len++)
        {
          vec1[i] = vec[wo_sign_indices_array[j][i]];
        }
      sort_int_vec(vec1, len);
      for (int i = 0; wo_sign_indices_array[j][i]; i++)
        {
          vec[wo_sign_indices_array[j][i]] = vec1[i];
        }
    }
}


void normalize_vec_last_len_elts(int * vec, int vec_len, int len)
{
  /* Action of -1. */
  int first_nonzero_idx;
  for (first_nonzero_idx = 0; first_nonzero_idx < vec_len; first_nonzero_idx++)
    {
      if (vec[first_nonzero_idx] != 0)
        {
          break;
        }
    }

  if (vec[first_nonzero_idx] < 0)
    {
      for (int i = 0; i < vec_len; i++)
        {
          vec[i] = - vec[i];
        }
    }

  /* Action of the last len elements */
  int vec1[16] = {0};
  for (int i = 0; i < len; i++)
    {
      vec1[i] = vec[i + vec_len - len];
    }
  _normalize_vec_w_sign(vec1, vec_len - len);
  for (int i = 0; i < len; i++)
    {
      vec[i + vec_len - len] = vec1[i];
    }
}
